[project]
name = "ec2-mcp"
version = "0.1.0"
description = "Simple MCP server for interacting with EC2"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.23",
    "dotenv>=0.9.9",
    "mcp>=1.25.0",
]
